name: Update icon
description: Request update for icon, if logo or main brand color is outdated.
title: "Update icon: "
labels: ["Update"]
body:
  - type: markdown
    attributes:
      value: |
        - :warning: Remember to **add name of the icon you want updated** at the end of *"Update icon:"* part on top, **do not change the formatting of the title!**
        - Don't request multiple updates in single issue, make issue for every singular update request.
        - [Read our issue guidelines first](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) if you haven't already (only takes half a minute to read!)
  - type: input
    id: site_app-url
    attributes:
      label: URL for the brand / site / app
      placeholder: Eg. https://example.com
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Remember to add *https://* (or *http://*) to start of the URL.

        - :warning: **Don't add Play Store link or other app store links**, unless requested entity doesn't have any other website.
  - type: dropdown
    id: update-reason
    attributes:
      label: Reason for update
      options:
        - New logo
        - Updated brand color
        - Other (write more info to "Anything else?" section)
    validations:
      required: true
  - type: input
    id: logo-url
    attributes:
      label: Logo resources for the icon
      placeholder: Eg. https://example.com/press-kit OR https://example.com/logo.svg
  - type: markdown
    attributes:
      value: |
        **Optional** option to add URL for *press kit* or *logo SVG vector*, preferably from official source ([tips for finding these](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#finding-source-images)).
        
        - :x: **Unaccepted resources:** JPG, PNG, GIF, WebP or [any other raster image](https://en.wikipedia.org/wiki/Image_file_format#Raster_formats).
        - :x: **NO [data URIs](https://en.wikipedia.org/wiki/Data_URI_scheme), SVG code** or anything **that's NOT web URL!** *(Forbidden because of long character lengths.)*
          - Data uri starts with: `data:image/svg+xml;,` (and so on)
          - SVG code starts with: `<svg` (and so on)
        
        *Adding a optional resource doesn't guarantee that aegis-icons will use it for the icon.*
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: Add other info, kudos etc.
  - type: markdown
    attributes:
      value: |
        **Required** if you selected `Other` as "reason for update".
