name: Icon request (app / site)
description: Suggest a new icon.
title: "Icon request: "
labels: ["New Icon"]
body:
  - type: markdown
    attributes:
      value: |
        - :warning: Remember to **add name of the site or app** at the end of *"Icon request:"* part on top, **do not change the formatting of the title!**
          - Please use proper capitalization for the name (check the capitalization from their app / website).
        
        [Read our issue guidelines first](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) if you haven't already (only takes half a minute to read!)
  - type: input
    id: site_app-url
    attributes:
      label: URL of the site or app
      placeholder: Eg. https://example.com
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Remember to add *https://* (or *http://*) to start of the URL.
  - type: input
    id: logo-url
    attributes:
      label: Logo resources for the icon
      placeholder: Eg. https://example.com/press-kit OR https://example.com/logo.svg
  - type: markdown
    attributes:
      value: |
        **Optional** option to add URL for *press kit* or *logo SVG vector*,  preferably from official source ([tips for finding these](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#finding-source-images)).
        
        - **Unaccepted resources:** JPG, PNG, GIF, WebP or [any other raster image](https://en.wikipedia.org/wiki/Image_file_format#Raster_formats).
        - :x: No [data URIs](https://en.wikipedia.org/wiki/Data_URI_scheme), please!
          - Starts with, for example: `data:image/svg+xml;base64,` and so on. Forbidden because of long character length.
        
        *Adding a optional resource doesn't guarantee that aegis-icons will use it for the icon.*
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: Optional text field to add other info, kudos etc.