name: Icon request (app / site)
description: Suggest a new icon.
title: "Icon request: "
labels: ["New Icon"]
body:
  - type: markdown
    attributes:
      value: |
        - :warning: Remember to **add name of the brand / site / app** at the end of *"Icon request:"* part on top, **do not change the formatting of the title!**
          - Please use proper capitalization for the name (check the capitalization from their app / website).
        - Don't request multiple icons in single issue, make issue for every singular icon request.
        - [Read our issue guidelines first](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) if you haven't already (only takes half a minute to read!)
  - type: input
    id: site_app-url
    attributes:
      label: Homepage URL for the brand / app
      placeholder: Eg. https://example.com
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Remember to add *https://* (or *http://*) to start of the URL.

        :heavy_exclamation_mark: **Don't add Play Store link or other app store links**, unless requested brand doesn't have website.
  - type: input
    id: logo-url
    attributes:
      label: Logo resources for the icon
      placeholder: Eg. https://example.com/press-kit OR https://example.com/logo.svg
  - type: markdown
    attributes:
      value: |
        **Optional** option to add URL for *press kit* or *logo SVG vector*, preferably from official source ([tips for finding these](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#finding-source-images)).
        
        - :x: **Unaccepted resources:** JPG, PNG, GIF, WebP or [any other raster image](https://en.wikipedia.org/wiki/Image_file_format#Raster_formats).
        - :x: **NO [data URIs](https://en.wikipedia.org/wiki/Data_URI_scheme), SVG code** or anything **that's NOT web URL,** please!
          - *Forbidden because of long character length.*
          - Data uri starts with: `data:image/svg+xml;base64,` (and so on)
          - SVG code starts with: `<svg` (and so on)
        
        *Adding a optional resource doesn't guarantee that aegis-icons will use it for the icon.*
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: Optional text field to add other info, kudos etc.