name: Icon request (generic)
description: Suggest a new *generic* icon (i.e. icon that doesn't represent any brand and uses symbols).
title: "Generic icon request: "
labels: ["New Icon", "Generic"]
body:
  - type: markdown
    attributes:
      value: |
        [Read our issue guidelines first](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) if you haven't already (only takes half a minute to read!)
        
        ⚠ Remember to **add symbol name** (eg. `education`) at the end of *"Generic icon request:"* part on top, **do not change the formatting of the title!**
        
        If you can't think of **symbol name**, use these sites as reference:
        - https://iconscout.com/unicons/explore/line
        - https://feathericons.com/
        - https://lucide.dev/
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: Optional text field to add other info, kudos etc.