name: Update icon
description: Request update for icon, if logo or main brand color is outdated.
title: "Update icon: "
labels: ["Update"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠ Remember to **add name of the site or app** at the end of *"Update icon:"* part on top, **do not change the formatting of the title!**
        
        [Read our issue guidelines first](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) if you haven't already (only takes half a minute to read!)
  - type: input
    id: site_app-url
    attributes:
      label: URL of the site or app
      placeholder: Eg. https://example.com
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Remember to add *https://* (or *http://*) to start of the URL.
  - type: dropdown
    id: update-reason
    attributes:
      label: Reason for update
      options:
        - New logo
        - Changed background color
        - Other (write more info to "Anything else?" section)
    validations:
      required: true
  - type: input
    id: logo-url
    attributes:
      label: Logo resources for the icon
      placeholder: Eg. https://example.com/press-kit OR https://example.com/logo.svg
  - type: markdown
    attributes:
      value: |
        **Optional** option to add URL for *press kit* or *logo SVG vector*,  preferably from official source ([tips for finding these](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#finding-source-images)).
        **Unaccepted resources:** JPG, PNG, GIF, WebP or [any other raster image](https://en.wikipedia.org/wiki/Image_file_format#Raster_formats).
        ❌ No [data URI](https://en.wikipedia.org/wiki/Data_URI_scheme) URLs, please!
        *Adding a optional resource doesn't guarantee that aegis-icons will use it for the icon.*
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: Add other info, kudos etc.
  - type: markdown
    attributes:
      value: |
        **Required** if you selected `Other` as "reason for update".
