blank_issues_enabled: false
contact_links:
  - name: Issues closed temporarily
    about: Computer issues (RAM module malfunction), I will not take more issues at this time. Hopefully fixed in under a week. DO NOT REQUEST ICONS IN THE ISSUE COMMENT SECTIONS!